#!/usr/bin/env perl
use v5.24;
use warnings;

use Math::Trig ':pi';

=pod

Determine the circumference of a circle with a radius of 12.5

=cut

my $radius = 12.5;
my $circumference = 2 * pi * $radius;

say $circumference;
