#!/usr/bin/env perl
use v5.24;
use warnings;

use Math::Trig ':pi';

=pod

Determine the circumference of a circle with a radius provided by the user.

=cut

print "Enter radius: ";
my $radius = <STDIN>;
my $circumference = 2 * pi * $radius;

say $circumference;
