#!/usr/bin/env perl
use v5.24;
use warnings;

=pod

Computes the product of two numbers provided by the user.

=cut

print "Enter your first number: ";
my $n1 = <STDIN>;

print "Enter your second number: ";
my $n2 = <STDIN>;

say $n1 * $n2;
