#!/usr/bin/env perl
use v5.24;
use warnings;

=pod

Repeats a user defined string by n times (n is also defined by the user).

=cut

print "Enter the string to repeat: ";
my $s = <STDIN>;

print "Enter number of times to repeat the string: ";
my $n = <STDIN>;

print $s x $n;
