#!/usr/bin/env perl
use v5.24;
use warnings;

=pod

Prints each line of input that mentions fred, now lets "Fred" match.

=cut

chomp(my @lines = <>);

foreach (@lines) {
  if (/\bfred\b/i) {
    say $_;
  }
}
