#!/usr/bin/env perl
use v5.24;
use warnings;

=pod

Reads a list of strings on seperate lines and prints out the list in reverse order.

=cut

say "Enter your list of strings below (Press Control-D on Unix or Control-Z on
Windows to indicate you are finished with your input):";

my @lines = <STDIN>;

say "\nThanks. Here is the input reversed:\n";

say reverse @lines;
