#!/usr/bin/env perl
use v5.24;
use warnings;

say "This program reads a list of strings on seperate lines and prints out the list in reverse order. Press Control-D on Unix or Control-Z on Windows to indicate you are finished with your input.";

say "Enter your list of strings below:";

my @lines = <STDIN>;

say "\nThanks. Here is the input reversed:\n";

say reverse @lines;
