#!/usr/bin/env perl
use v5.24;
use warnings;

say "This program reads a list of numbers (on seperate lines) and then prints a corresponding name for each number. Press Control-D on Unix or Control-Z on Windows to indicate you are finished with your input.";

my @names = qw(fred betty barney dino wilma pebbles bamm-bamm);

say "Enter your numbers (1-7) below:";

my @lines = <STDIN>;

say "\nHere are the names:";

foreach my $index (@lines) {
  print "$names[$index - 1] ";
}
