#!/usr/bin/env perl
use v5.24;
use warnings;

say "This program reads a list of strings (on seperate lines) the prints them in code point order. Press Control-D on Unix or Control-Z on Windows to indicate you are finished with your input.";

say "Input your list of strings below (on seperate lines):";

chomp(my @lines = <STDIN>);

say "\nHere are the strings in sorted order:";

say join(" ", sort @lines);
