#!/usr/bin/env perl
use v5.24;
use warnings;

=pod

Reads a list of strings then prints them in code point order.

=cut

say "Input your list of strings below (Press Control-D on Unix or Control-Z on Windows to indicate you are finished with your input):";

chomp(my @lines = <STDIN>);

say "\nHere are the strings in sorted order:";

say join(" ", sort @lines);
