#!/usr/bin/env perl
use v5.24;
use warnings;

=pod

Matches the string "match" and prints the special variables in order.

=cut


while (<>) {           # take one input line at a time
  chomp;
  if (/match/) {
    print "Matched: |$`<$&>$'|\n";  # the special match vars
  } else {
    print "No match: |$_|\n";
  }
}
