#!/usr/bin/env perl

=pod

Removes "<" and ">" from "perldoc -u -f atan2". Challenge was to tye it out
and get it working.

=cut

my @lines = `perldoc -u -f atan2`;

foreach (@lines) {
  s/\w<([^>]+)>/\U$1/g;
  print;
}
